### ISSUE TITLE
Program freezing

### ISSUE THREAD

**Issue by DiCE1904** [GetEnvy/Envy#2]
Program freezes anytime I try and close a search. 
Using windows 10. Tried also in compatibility mode windows 7 and 8 and getting the same freeze.

**Comment by SkinVista** [comment]
Can Not Reproduce.

Thank-you for the report, this sounds like a urgent bug. (Blocking)
However, I haven't been able to recreate the behavior locally.
(32/64-bit installs on various 64-bit Windows10 machines)

I will continue to look into this, but any other information might help.

**Comment by DiCE1904** [comment]
What can I do or how can I give you more info about this? Would there be a log dump somewhere that might help?

**Comment by DiCE1904** [comment]
Did a fresh install and it seems like I only get the freeze with Envy Carbon theme

**Comment by SkinVista** [comment]
Thanks, I was indeed able to produce a freeze with the Carbon skin.
Working to pin down the problem for a fix.

**Comment by SkinVista** [comment]
Fix Carbon skin for r16 (1.0 silent update),
underlying defect remains to-do.
