### ISSUE TITLE
It does not work in Windows 10 x64

### ISSUE THREAD

**Issue by Havokdan** [GetEnvy/Envy#6]
It does not work in Windows 10 x64

**Comment by Livxx** [comment]
Does not work in Windows 7 x64

**Comment by shui0855** [comment]
it can't launch in my os of win10 x64 1903:
program: D:\Program Files\Envy\Envy.exe
error module: C:\Windows\SYSTEM32\ntdll.dll
error code: 0xc0000374, offset: 0x00000000000f9269

**Comment by Havokdan** [comment]
Yes, now open. :D
