### ISSUE TITLE
Will the next version fix the support for win10 x64？

### ISSUE THREAD

**Issue by Livxx** [GetEnvy/Envy#7]
Envy2.0 can't open at all.
Thank you very much for your work.

**Comment by bleuge** [comment]
Same here, installed in W10x64, ran it, shows starting dialog, and thats all. Does nothing?

**Comment by SkinVista** [comment]
Please try Envy 3.0 to fix the startup issue.

**Comment by bleuge** [comment]
Envy3.0.exe was what I tried, just 5minutes ago from the releases tab.

**Comment by SkinVista** [comment]
Thanks, I'll keep digging. Also try the debug build: [Envy.3.0.64.Debug.exe](https://sourceforge.net/projects/getenvy/files/Envy.3.0/Envy.3.0.64.Debug.exe/download)

**Comment by Livxx** [comment]
Envy 4.0 has solved this problem.Thanks for you work.
